export const curators = [
  {
    name: 'Caiti',
    title: 'Wellness and Health Expert',
    bio: '',
    top_gift_name: '',
    top_gift_url: '',
    ratings_count: 5,
    rating: 0,
    gifts_curated: 23 ,
    areas: ['health', 'yoga', 'well-being', 'make up', 'hair'],
  },
  {
    name: 'Nati',
    title: 'Sporting and Fitness Fanatic',
    bio: '',
    top_gift_name: '',
    top_gift_url: '',
    ratings_count: 23,
    rating:0,
    gifts_curated: 39 ,
    areas: ['fitness', 'running shoes', 'sports equipment'],
  },
  {
    name: 'Katherine',
    title: 'Head Curator',
    bio: '',
    top_gift_name: '',
    top_gift_url: '',
    ratings_count: 23,
    rating: 0 ,
    gifts_curated: 51,
    areas: ['homemaking', 'art', 'cooking', 'holiday decorating', 'gifts for any age'],
  },
  {
    name: 'Turner',
    title: 'Outdoorsman',
    bio: '',
    top_gift_name: '',
    top_gift_url: '',
    ratings_count: 23,
    rating:0,
    gifts_curated: 31,
    areas: ['fishing', 'golf', 'camping'],
  },
  {
    name: 'Sam',
    title: 'Fashion Icon (Men)',
    bio: '',
    top_gift_name: '',
    top_gift_url: '',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 2 ,
    areas: ['men"s fashion', 'DJ equipment', 'musical instruments'],
  },
  {
    name: 'Leland',
    title: 'Mr. Activity',
    bio: '',
    top_gift_name: '',
    top_gift_url: '',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 19,
    areas: ['golf', 'ski', 'BMX', 'basketball shoes'],
  },
  {
    name: 'Nicole',
    title: 'Teen Boy and Fashion Expert',
    bio: '',
    top_gift_name: '',
    top_gift_url: '',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 20 ,
    areas: ['young teen', 'fashion', 'home improvement', 'jewelery'],
  },
  {
    name: 'Kaylin',
    title: 'Supermom',
    bio: '',
    top_gift_name: '',
    top_gift_url: '',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 17,
    areas: ['little ones', 'toys', 'wine'],
  },
  {
    name: 'Hunter',
    title: 'Gamer and Electronics Expert',
    bio: '',
    top_gift_name: '',
    top_gift_url: '',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 6,
    areas: ['video games', 'headphones', 'computer stuff'],
  },
  {
    name: 'Bronwyn',
    title: 'Fashion Icon (Women)',
    bio: '',
    top_gift_name: '',
    top_gift_url: '',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 16,
    areas: ['clothing', 'shoes', 'Luxury Pens'],
  },
  {
    name: 'Malcolm',
    title: 'The Sports Guy',
    bio: '',
    top_gift_name: '',
    top_gift_url: '',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 37,
    areas: ['sports memorabilia', 'baseball cards']
  }
]
