export const curators = [
  {
    name: 'Caiti',
    title: 'Wellness and Health Expert',
    bio: '',
    top_gift_name: 'Little Fires Everywhere',
    top_gift_url: 'https://amzn.to/37HeA8l',
    ratings_count: 5,
    rating: 0,
    gifts_curated: 23 ,
    areas: ['health', 'yoga', 'well-being', 'make up', 'hair'],
  },
  {
    name: 'Nati',
    title: 'Sporting and Fitness Fanatic',
    bio: '',
    top_gift_name: 'Fabric Booty Bands',
    top_gift_url: 'https://amzn.to/2VNCLfP',
    ratings_count: 23,
    rating:0,
    gifts_curated: 39 ,
    areas: ['fitness', 'running shoes', 'sports equipment'],
  },
  {
    name: 'Katherine',
    title: 'Head Curator',
    bio: '',
    top_gift_name: 'Serving Platter - Plexi',
    top_gift_url: 'https://katherinehoustonart.com/product/plexiglass-tray-1/',
    ratings_count: 23,
    rating: 0 ,
    gifts_curated: 51,
    areas: ['homemaking', 'art', 'cooking', 'holiday decorating', 'gifts for any age'],
  },
  {
    name: 'Turner',
    title: 'Outdoorsman',
    bio: '',
    top_gift_name: 'Shimano Calcutta Conquest Reel',
    top_gift_url: 'https://amzn.to/2Il3mhn',
    ratings_count: 23,
    rating:0,
    gifts_curated: 31,
    areas: ['fishing', 'golf', 'camping'],
  },
  {
    name: 'Sam',
    title: 'Fashion Icon (Men)',
    bio: '',
    top_gift_name: 'Carhartt Men"s Arcrylic Beanie',
    top_gift_url: 'https://amzn.to/3ouxJRT',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 2 ,
    areas: ['men"s fashion', 'DJ equipment', 'musical instruments'],
  },
  {
    name: 'Leland',
    title: 'Mr. Activity',
    bio: '',
    top_gift_name: 'Titleist Pro V1 Golf Balls',
    top_gift_url: 'https://amzn.to/3lOUfDa',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 19,
    areas: ['golf', 'ski', 'BMX', 'basketball shoes'],
  },
  {
    name: 'Nicole',
    title: 'Teen Boy and Fashion Expert',
    bio: '',
    top_gift_name: 'Kids Drone with Camera',
    top_gift_url: 'https://amzn.to/2JTnB68',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 20 ,
    areas: ['young teen', 'fashion', 'home improvement', 'jewelery'],
  },
  {
    name: 'Kaylin',
    title: 'Supermom',
    bio: '',
    top_gift_name: 'Baby Onesie - Elephant',
    top_gift_url: 'https://amzn.to/33PCRbe',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 17,
    areas: ['little ones', 'toys', 'wine'],
  },
  {
    name: 'Hunter',
    title: 'Gamer and Electronics Expert',
    bio: '',
    top_gift_name: 'Bose QuietComfort Earbuds',
    top_gift_url: 'https://amzn.to/37K92Ki',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 6,
    areas: ['video games', 'headphones', 'computer stuff'],
  },
  {
    name: 'Bronwyn',
    title: 'Fashion Icon (Women)',
    bio: '',
    top_gift_name: 'Birthstone Pendant Necklace',
    top_gift_url: 'https://www.kendrascott.com/products/elisa-gld.html?dwvar_elisa-gld_stoneColor=618&cgid=birthstone-inspired%23start%3D1',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 16,
    areas: ['clothing', 'shoes', 'luxury pens'],
  },
  {
    name: 'Malcolm',
    title: 'The Sports Guy',
    bio: '',
    top_gift_name: 'LA Dodgers World Series Baseball',
    top_gift_url: 'https://amzn.to/3mPEA8b',
    ratings_count: 23,
    rating:0 ,
    gifts_curated: 37,
    areas: ['sports memorabilia', 'baseball cards']
  }
]
